services:
  anki-api:
    build:
      context: .
    environment:
      PORT: 9000
      MONGO_URL: mongodb://anki-db_dev:27017/anki-clone
      ACCESS_TOKEN_SECRET: mysupersecrettoken
      REFRESH_TOKEN_SECRET: mysupersecrettoken2
      SALT: mysupersecretsalt
      NODE_ENV: production
    ports:
      - 9000:9000
  anki-db_dev:
    container_name: anki-db_dev
    image: mongo:7.0.2-jammy
    ports:
      - 27017:27017
    volumes:
      - mysql-data:/data/db

volumes:
  mongodb-data:
